# Arma FUENTES.txt: archivo | bytes | URL | fecha de consulta | descripción
import os
U='/tmp/claude-0/-home-user-casares-sanisidro-2027/19687d82-9b19-5a6f-8ec4-f8d897955d9f/scratchpad/puestos_raw/u1_cloaca_playones_bosque'
R='/tmp/claude-0/-home-user-casares-sanisidro-2027/19687d82-9b19-5a6f-8ec4-f8d897955d9f/scratchpad/ch/wt/'
H='2026-10-03'
ESRI='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/19/{y}/{x}'
D={
'aysa/aysa_2022-11_enlace_colector_bajo_costanero.html':('https://www.aysa.com.ar/sistema_riachuelo/novedades/AySA_trabaja_enlace_Colector_Bajo_Costanero_Sistema_Riachuelo','AySA, 26/11/2022: el Colector Costanero (3,5 m) lleva efluentes "desde la zona norte del Gran Buenos Aires" a la EBC Boca-Barracas. No da traza en San Isidro'),
'aysa/aysa_la_red_de_desagues_cloacales.pdf':('https://www.aysa.com.ar/media-library/usuarios/informacion_util/datos_utiles_para_el_usuario/la_red_de_desagues_cloacales.pdf','AySA, folleto: la puesta a disposición de la cloaca obliga a volcar efluentes residenciales y no residenciales (comercios) y cegar pozos; esquema de límites de responsabilidad (conexión AySA hasta línea municipal; red interna del usuario)'),
'aysa/cavera_2020-05_listado_proyectos_AySA_por_municipio.pdf':('https://cavera.org.ar/images/slider/mayo20/14.pdf','Cámara vial (secundaria), mayo 2020: listado de proyectos por municipio; para San Isidro/AySA/cloacas sólo NC70130 "Red primaria cloacal impulsión definitiva Boulogne Oeste 1" (lejos de la costa)'),
'muni/muni_mas_vecinos_beccar_red_cloacal.html':('https://www.sanisidro.gob.ar/novedades/m%C3%A1s-vecinos-de-beccar-con-servicio-de-red-cloacal','Municipio, 24/07/2019: AySA construye red secundaria "Sucre Zona III" en Béccar (Sucre, Rolón, Copello: lejos de la costa). Consultada, no aplica a los puestos'),
'muni/muni_mas_vecinos_beccar_servicio_cloacal.html':('https://www.sanisidro.gob.ar/novedades/m%C3%A1s-vecinos-de-beccar-con-servicio-cloacal','Municipio, 30/10/2019: AySA terminó "Sucre Zona III" (2.800 m, 283 conexiones). Consultada, no aplica a los puestos'),
'muni/muni_noticia1197_avanza_renovacion_puerto_libre.html':('https://www.sanisidro.gob.ar/noticia/1197/avanza-la-renovacion-de-puerto-libre','Municipio, 25/10/2017: Puerto Libre: baños para personas con discapacidad, 4 sanitarios con duchas, "cañerías de última generación"'),
'muni/muni_primer_sector_parque_publico_puerto.html':('https://www.sanisidro.gob.ar/novedades/se-inaugur%C3%B3-el-primer-sector-del-parque-p%C3%BAblico-del-puerto','Municipio, 08/10/2019: primer sector (10.000 m2) del Parque Público del Puerto; "rotonda y nuevos asfaltos en el triángulo Tiscornia, Primera Junta y Mitre"'),
'muni/muni_areas_protegidas.html':('https://www.sanisidro.gob.ar/areas-protegidas','Municipio: 5 áreas protegidas; Bosque Alegre es "Paisaje Protegido", 4,5 ha según el Municipio; el Parque Público del Puerto integra el Corredor Ecológico'),
'muni/muni_verano_opciones_aire_libre_dj_sunset.html':('https://www.sanisidro.gob.ar/novedades/cine-m%C3%BAsica-teatro-y-espect%C3%A1culos-al-aire-libre-conoce-todas-las-opciones-para-el-verano','Municipio, 27/01/2026: "Dj Sunset frente al río, estará los domingos de 17 a 22.30h en el Centro Municipal de Exposiciones, con food trucks" (agenda hasta 29/03/2026)'),
'muni/muni_noticia1850_obras_bajo_500_familias.html':('https://www.sanisidro.gob.ar/noticia/1850/las-obras-del-bajo-de-san-isidro-beneficiaran-a-mas-de-500-familias','Municipio, 12/07/2018: obras de hábitat en el Bajo (El Fomentista, R. Sáenz Peña, Gaboto, Martín y Omar, Pedro de Mendoza): pavimento, gas y "luego, la red de cloacas en ambos lados del pavimento"; desagüe pluvial de Martín y Omar "entre calle 1 y El Fomentista" hacia la estación de bombeo Martín y Omar'),
'prensa/norteenlinea_feria_argentina_2026_CME.html':('https://norteenlinea.com/reinterpretar-lo-nuestro-la-propuesta-de-la-feria-argentina-2026-para-conectar-el-pasado-con-el-presente/','Prensa (secundaria), 23/09/2026: "La Feria Argentina" 14-15/11/2026 en el Centro Municipal de Exposiciones "(Del Barco Centenera y el Río, Calle 1 interna)", patio gastronómico y foodtrucks, "con el apoyo de la Municipalidad"'),
'normas/PBA_Ley12704_paisaje_protegido_normasgba.html':('https://normas.gba.gob.ar/documentos/xqzvWFpB.html','Ley provincial 12.704 (Paisaje Protegido / Espacio Verde de Interés Provincial): texto completo; art. 1 "deberán ser declaradas por ley"; art. 7 EIA con carácter restrictivo para "establecimientos ... comerciales en el lugar o en zonas aledañas"'),
'normas/SI_digesto_Ord8641_banos_uso_publico_locales_comerciales.pdf':('https://boletines.sanisidro.gob.ar/digesto/2%20HABILITACIONES/2.5.%20Ba%C3%B1os%20para%20uso%20p%C3%BAblicos%20en%20locales%20comerciales/2.5.2._Ordenanza_n%C2%BA_8641.pdf','Digesto SI: Ord. 8641 (04/04/2012) = baños para menores en centros comerciales. Muestra que la "Ordenanza 8641" citada en el Dec. 910/2012 es un error por la 8461'),
'normas/SI_digesto_Ord5824_parque_municipal_ribera.pdf':('https://boletines.sanisidro.gob.ar/digesto/1%20ASUNTOS%20VARIOS/1.1%20ACCION%20SOCIAL/1.46%20RIBERA/1.46.7%20PARQUE%20MUNICIPAL/1.46.7.1._Ordenanza_n%C2%BA_5824.pdf','Digesto SI: Ord. 5824 (01/03/1983) crea el Parque Municipal de la Ribera y sus 8 sectores: usos comerciales, estacionamiento y, en el S.4, regla para "el parque denominado Bosque Alegre" (sólo kioscos de bebidas; confitería sobre pilotes en la prolongación de Stella Maris)'),
'normas/SI_digesto_Ord8461_areas_naturales_protegidas.pdf':('https://boletines.sanisidro.gob.ar/digesto/1%20ASUNTOS%20VARIOS/1.1%20ACCION%20SOCIAL/1.24%20ECOLOGIA/1.24.8._Ordenanza_n%C2%B0_8461.pdf','Digesto SI: Ord. 8461 (19/08/2009), Sistema Municipal de Áreas Naturales Protegidas; arts. 3, 5 (Paisaje Protegido) y 11 (prohibiciones, sólo para Parques Naturales)'),
'normas/SI_digesto_OG27_ruidos_molestos.pdf':('https://boletines.sanisidro.gob.ar/digesto/1%20ASUNTOS%20VARIOS/1.1%20ACCION%20SOCIAL/1.47%20RUIDOS%20MOLESTOS/1.47.1._Ordenanza_General_n%C2%BA_27.pdf','Ordenanza General 27/1968 (provincial, en el digesto de SI): ruidos molestos en parques y paseos; sin límites en decibeles'),
'normas/SI_digesto_OG224_ruidos_molestos.pdf':('https://boletines.sanisidro.gob.ar/digesto/1%20ASUNTOS%20VARIOS/1.1%20ACCION%20SOCIAL/1.47%20RUIDOS%20MOLESTOS/1.47.3._Ordenanza_General_n%C2%BA_224.pdf','Ordenanza General 224/1978: modifica el art. 4 c) de la OG 27'),
'normas/SI_BO_EdExtra645_2012_Dec910-2012_Bosque_Alegre.pdf':('https://boletines.sanisidro.gob.ar/uploads/boletin/Ediciones-Extras-645-2012-04-01.pdf','BO SI Edición Extra 645 (11/04/2012): Decreto 910/2012 (copiado del repo 01_raw/agua/5_parques/). Art. 2: Paisaje Protegido Bosque Alegre, límites y 6 coordenadas; cita "art. 3 inc. b) de la Ordenanza 8641"'),
'normas/SI_BO859_2012_Ord8651_convalida_Dec910.pdf':('https://boletines.sanisidro.gob.ar/uploads/boletin/Boletines-Oficiales-2a-quincena-859-2012-05-01.pdf','BO SI 859 (mayo 2012): Ord. 8651 (16/05/2012) "Convalídase lo actuado ... mediante Decreto Nº 910"; Dec. 1173/2012 la promulga (copiado del repo)'),
'normas/SI_BO_EdExtra456_2009_Ord8461_texto.txt':('https://boletines.sanisidro.gob.ar/uploads/boletin/Ediciones-Extras-456-2009-09-01.pdf','Texto de la Edición Extra 456 (10/09/2009): Ord. 8460 y 8461 (copiado del repo 01_raw/agua/5_parques/work/ord8461.txt)'),
'normas/SI_digesto_Dec280-1973_Balneario_Bosque_Alegre.pdf':('https://boletines.sanisidro.gob.ar/digesto/1%20ASUNTOS%20VARIOS/1.1%20ACCION%20SOCIAL/1.46%20RIBERA/1.46.2%20BOSQUE%20ALEGRE/1.46.2.1._Decreto_n%C2%BA_280-1973.pdf','Dec. 280/1973: crea el Balneario Municipal Bosque Alegre (~8 ha) con acceso gratuito; prevé "agua, luz, servicios sanitarios" sin alterar "su fisonomía natural y agreste" (copiado del repo)'),
'normas/SI_digesto_Dec280-1973_Balneario_Bosque_Alegre_OCR.txt':('(OCR del anterior, repo)','texto OCR'),
'normas/PBA_ResMEcon138-2026_AnexoII_convenio_OCR.txt':('https://normas.gba.gob.ar/anexos/descargar/7BjYy5kx.pdf (OCR del repo)','Convenio de tenencia Res. 138/2026: cláusulas 4ª (40% de cánones a la Provincia), 6ª (usos gastronómicos, sanitarios... con canon) y 7ª (prohíbe limitar la libre circulación; obras con comunicación previa)'),
'normas/CALCULO_PROPIO_superficie_15_parcelas_AnexoI_Res138-2026.csv':('(repo 01_raw/costa_viva/1_tenencia_y_canon/)','Lista de las 15 parcelas del Anexo I con CCA de ARBA [cálculo propio del trabajo anterior]'),
'normas/SI_Dec1154-2025_CONVE-2025-69_adenda_OCR.txt':('https://tesi.sanisidro.gob.ar/nfs-storage/gde/v2/gde_1759512964.pdf (OCR del repo)','Dec. 1154/2025, adenda con un club: canchas con riego e iluminación junto a Bosque Alegre (2025-2027); "integración de Bosque Alegre, respetando su paisaje natural"'),
'normas/SI_Dec605-2025_SIPUC_texto.txt':('https://tesi.sanisidro.gob.ar/nfs-storage/gde/v2/gde_1750793065.pdf (texto del repo)','Dec. 605/2025: SI PUC; 33 Orientales con "dársenas de estacionamiento y una bajada náutica"; etapa 2 "senderos hacia el Bosque Alegre"'),
'normas/SI_Ord9434-2026_OCR.txt':('(repo; Boletín #1232)','Ord. 9434 (20/05/2026): desafecta 746,54 m2 de Camino de la Ribera-El Fomentista entre Stella Maris y Del Barco Centenera (Manzana 30, Secc. A)'),
'normas/SI_COU_TO2022_extractos_pags_101-102_211-213_247-248.txt':('https://www.sanisidro.gob.ar/sites/default/files/img/codigo_de_ordenamiento_urbano_-_to_2022_compressed_compressed_1.pdf (texto del repo)','COU TO 2022: art. 1.2.4.8 Parque Municipal de la Ribera; Hoja de Zona EPr (cloaca "a red existente o bien Planta de Tratamiento"; cotas +2,35 y +4,44 IGN); Anexo Ord. 8461'),
'normas/PlanManejo_RiberaNorte_2012_extractos_pags_24-26_60-61_69_124.txt':('https://www.losquesevan.com/archivos/plan-de-manejo-ribera-norte.pdf (texto del repo)','Plan de Manejo PNM Ribera Norte 2012: albardón y cloacas en el Bajo (pág. 24-26), "No se instaló el servicio cloacal por temor a comprometer la eficacia de la defensa costera" (pág. 60), vivero con cloaca (pág. 69), Proyecto 21: la red "existe en las adyacencias del área" (pág. 124)'),
'licitaciones/SI_LP19-2026_banos_pliego_particular.pdf':('https://www.sanisidro.gob.ar/sites/default/files/img/pliego_particular_0.pdf (copiado de d2)','LP 19/2026 alquiler de baños químicos, renglones: Parque 33 Orientales (22), Del Barco Centenera 1014 Centro de Exposiciones (26 y 27), R. Sáenz Peña 1260 Planta de Áridos (29 y 30), Tiscornia 1100 (32), Del Barco Centenera y Pedro de Mendoza (33)'),
}
for f in os.listdir(f'{U}/muni'):
    if f.startswith('repo_') and f.endswith('.html'):
        D['muni/'+f]=('(copiado del repo; URL en su FUENTES)','Nota del Municipio guardada en el repo (eventos en el Centro Municipal de Exposiciones, Nochecitas en el río, Paseo 33 Orientales, obras Puerto Libre)')
URLS_REPO={'repo_novedad_2022-11-07':'https://www.sanisidro.gob.ar/novedades/mas-de-40-mil-personas-disfrutaron-del-festival-gastronomico-bocas-abiertas','repo_novedad_2023-02-13':'https://www.sanisidro.gob.ar/novedades/mas-de-15-mil-personas-disfrutaron-del-parador-konex','repo_novedad_2023-11-06':'https://www.sanisidro.gob.ar/novedades/miles-de-personas-disfrutaron-de-una-nueva-edicion-del-festival-gastronomico-bocas','repo_novedad_2024-09-04':'https://www.sanisidro.gob.ar/novedades/el-festival-warmichella-llega-este-fin-de-semana-al-centro-municipal-de-exposiciones','repo_novedad_2025-05-09':'https://www.sanisidro.gob.ar/novedades/fin-de-semana-procesi%C3%B3n-n%C3%A1utica-warmichella-muestra-hist%C3%B3rica-en-el-museo-del-juguete-y','repo_novedad_2026-04-29':'https://www.sanisidro.gob.ar/novedades/expo-mate-2026-con-la-recaudaci%C3%B3n-donar%C3%A1n-equipos-al-hospital-central','repo_novedad_2026-06-17':'https://www.sanisidro.gob.ar/novedades/donaci%C3%B3n-de-expo-mate-2026-se-entregaron-equipos-de-alta-tecnolog%C3%ADa-en-el-hospital-central','repo_muni_2026-01-23':'https://www.sanisidro.gob.ar/novedades/llega-%E2%80%9Cnochecitas-en-el-rio-para-disfrutar-la-costa-con-gastronom%C3%ADa-y-m%C3%BAsica','repo_muni_2026-02-18':'https://www.sanisidro.gob.ar/novedades/nueva-edici%C3%B3n-de-%E2%80%9Cnochecitas-en-el-rio-para-disfrutar-la-costa-con-gastronom%C3%ADa-y-m%C3%BAsica','repo_muni_2025-05-05':'https://www.sanisidro.gob.ar/novedades/qued%C3%B3-inaugurado-el-nuevo-paseo-costero-en-la-zona-de-treinta-y-tres-orientales','repo_muni_2026-07-20':'https://www.sanisidro.gob.ar/novedades/comienzan-obras-estructurales-en-puerto-libre'}
DESC_REPO={'repo_novedad_2022-11-07':'Municipio, 07/11/2022: Bocas Abiertas (10ª) en el Centro Municipal de Exposiciones, 4 jornadas, más de 40.000 personas, más de 40 stands "de restó y food trucks"','repo_novedad_2023-02-13':'Municipio, 13/02/2023: Parador Konex en el CME, más de 15.000 personas, food trucks','repo_novedad_2023-11-06':'Municipio, 07/11/2023: Bocas Abiertas (11ª) en el CME, 3 jornadas, más de 30 stands de restó y food trucks','repo_novedad_2024-09-04':'Municipio, 04/09/2024: Warmichella 7 y 8/09/2024 en el CME, "más de nueve" foodtrucks','repo_novedad_2025-05-09':'Municipio, 09/05/2025: Warmichella 10 y 11/05/2025 en el CME (Del Barco Centenera y el río), foodtrucks','repo_novedad_2026-04-29':'Municipio, 29/04/2026: Expo Mate 23-25/05/2026 en el CME, predio "ampliado a 9.500 metros cuadrados"','repo_novedad_2026-06-17':'Municipio, 17/06/2026: donación de lo recaudado en Expo Mate 2026','repo_muni_2026-01-23':'Municipio, 23/01/2026: Nochecitas en el río (R. Sáenz Peña y el río) con puestos de gastronomía','repo_muni_2026-02-18':'Municipio, 18/02/2026: nueva edición de Nochecitas en el río (20/02/2026)','repo_muni_2025-05-05':'Municipio, 05/05/2025: Paseo 33 Orientales, 5.000 m2, bebederos, bicicleteros','repo_muni_2026-07-20':'Municipio, 20/07/2026: obras en Puerto Libre (90 días): "puesta en valor y ampliación de las instalaciones cloacales y de la red pluvial"'}
lines=['# FUENTES · u1_cloaca_playones_bosque (puestos náuticos: cloaca, playones y Bosque Alegre) · 03/10/2026','# archivo | bytes | URL | fecha de consulta | descripción','# Los .html/.pdf tienen al lado su .txt (texto extraído con scripts/h2t.py o scripts/pdf2txt.py, PyMuPDF).','# Imágenes: Esri World Imagery (teselas públicas, sin registro). Atribución: Esri, Maxar/Vantor, Earthstar Geographics, and the GIS User Community. Fecha real de captura en imagenes/esri_metadatos_fecha_captura.json','']
files=sorted(open(f'{U}/work/lista_archivos.txt').read().split())
for f in files:
    p=f'{U}/{f}'
    if not os.path.exists(p): continue
    b=os.path.getsize(p)
    if f in D: url,desc=D[f]
    elif f.endswith('.txt') and (f[:-4]+'.html' in D or f[:-4]+'.pdf' in D): url,desc='(texto del anterior)','texto extraído'
    elif f.startswith('muni/repo_'):
        k=[x for x in URLS_REPO if os.path.basename(f).startswith(x)]
        k=k[0] if k else None
        url=(URLS_REPO.get(k,'(repo)')+' (copiado del repo)') if f.endswith('.html') else '(texto del anterior)'
        desc=DESC_REPO.get(k,'') if f.endswith('.html') else 'texto extraído'
    elif f.startswith('imagenes/') and f.endswith('.png'): url,desc=ESRI,'Mosaico de teselas z19 (≈0,25 m/px) de Esri World Imagery alrededor del sitio; bbox en el .json'
    elif f.startswith('imagenes/') and f.endswith('.json') and 'metadatos' not in f: url,desc='(elaboración propia)','Georreferencia del mosaico (bbox lon/lat, zoom, fuente)'
    elif f=='imagenes/esri_metadatos_fecha_captura.json': url,desc='https://metadata.maptiles.arcgis.com/arcgis/rest/services/World_Imagery_Metadata_2026_r07/MapServer/4/query','Fecha real de captura por sitio: 03/01/2026 WV03 0,31 m (Vantor); 33 Orientales 28/12/2025 WV02 0,5 m'
    elif f.startswith('recortes/') and 'marcados' in f: url,desc='(elaboración propia sobre Esri World Imagery)','[cálculo propio / probable] Recorte con las superficies candidatas marcadas y rotuladas (ver calculos/CALCULO_PROPIO_playones_desde_imagen.csv); grilla en metros desde el centro del recorte; rojo = polígono Dec. 910/2012; naranja = parcelas del convenio; amarillo = otras parcelas ARBA; cian = playones OSM'
    elif f.startswith('recortes/'): url,desc='(elaboración propia sobre Esri World Imagery + ARBA + OSM)','Mosaico anotado: grilla 25/50 m, parcelas ARBA (naranja = convenio Res. 138/2026), playones (cian) y parques (verde) de OSM, polígono del Paisaje Protegido (rojo)'
    elif f.startswith('calculos/'): url,desc='(elaboración propia, scripts/)','[cálculo propio] '+('Superficies medidas sobre imagen por sitio: área del polígono, área sin vegetación (ExG<12), parcela ARBA, distancia al Paisaje Protegido' if 'playones' in f else 'Proxy de colectora más cercana: parcela urbana chica (<2.500 m2, fuera del convenio) y parcela con edificio más cercanas a cada borde')
    elif f.startswith('scripts/'): url,desc='herramienta','script usado'
    elif f.startswith('work/'): url,desc='herramienta / trabajo','archivo de trabajo (vistas reducidas, zooms, certificados intermedios públicos, config de Wayback)'
    else: url,desc='',''
    lines.append(f'{f} | {b} | {url} | {H} | {desc}')
lines+=['','# ---------------------------------------------------------------------------------------------','# MATERIAL DEL REPOSITORIO / TRABAJOS ANTERIORES LEÍDO Y NO COPIADO (rutas bajo '+R+' o scratchpad/puestos_raw/)','# ---------------------------------------------------------------------------------------------',
'puestos_raw/d1_terreno/ (informe reportes/puestos_D1_terreno.md, OSM API 0.6 osm/*.osm, ARBA arba/*.json, calculos/*.json|csv, polígono CALCULO_PROPIO_poligono_Dec910-2012_Bosque_Alegre.geojson) | base de las mediciones (no se repitió la descarga)',
'puestos_raw/d2_foodtrucks_banos/ e informe reportes/puestos_D2_foodtrucks_banos.md | LP 19/2026 (copiado el pliego particular), normas de baños',
'informes/14_parques_y_costa.md, 16_agua_y_costa.md, 17_costa_viva.md, 20_puestos_nauticos_y_abl.md | contexto (Bosque Alegre, playones por tramo, Centro de Exposiciones en la semana)',
'01_raw/parques/4_naturaleza_contra_cemento/plan-de-manejo-ribera-norte.pdf (19,8 MB) | se guardó sólo el extracto de texto (normas/PlanManejo_...)',
'01_raw/parques/3_ribera_despues_del_veto/codigo_de_ordenamiento_urbano_-_to_2022_compressed_compressed_1.pdf | se guardó sólo el extracto (normas/SI_COU_...)',
'01_raw/costa_viva/1_tenencia_y_canon/ResMEcon138-2026_AnexoII.pdf | se guardó el OCR',
'01_raw/agua/5_parques/gde_1759512964_DECRE-2025-1154.pdf | se guardó el OCR',
'01_raw/costa_viva/3_transito_hoy/osm/api_tiles/*.osm (14 tiles, 01/10/2026) | búsqueda de man_made=manhole/wastewater/pumping_station: sólo un pumping_station en Vicente López (node 8151855701)',
'data/censo2022_sanisidro_por_radio.csv y radios (vía d1) | % de hogares con cloaca por radio (no se recalculó)',
'scratchpad/bol_all.txt (índice de 15.466 entradas del Boletín Oficial de SI hasta el #1238, 08/09/2026) | búsqueda de cloaca/estacionamiento/dársena/Exposiciones/Bosque Alegre en la costa: sólo licitaciones genéricas de desobstrucción de redes (LP 60/2024, LP 67/2025) y actos de Puerto Libre (comida, transporte), ninguno de red cloacal ni de estacionamientos costeros',
'scratchpad/u5_work/digesto_listado.txt | listado del digesto municipal (de ahí salieron las URL de Ord. 5824, 8461, 8641, OG 27 y 224)',
'','# ---------------------------------------------------------------------------------------------','# PÁGINAS LEÍDAS Y NO GUARDADAS / CONSULTAS FALLIDAS (2026-10-03)','# ---------------------------------------------------------------------------------------------',
'WebSearch (varias): AySA colector ribereño/costanero traza; estaciones de bombeo cloacal en San Isidro; mapa de cobertura AySA por dirección; ERAS, ENOHSA y APLA (sólo notas generales; ENOHSA en cierre, sin obras en la costa de SI); Parque Público del Puerto sanitarios; Bocas Abiertas; Ley 12.704; Ley 15.185 | sólo resultados de búsqueda; lo que se usó se bajó arriba',
'https://www.aysa.com.ar (oficina virtual / factibilidad) | la consulta de servicio y factibilidad por dirección pide cuenta o registro: no se usó',
'https://www.aysa.com.ar/data/gestion_datos (ya en d1) | cobertura sólo por partido',
'https://imagenes.ign.gob.ar/geoserver/wms GetFeatureInfo capa mde_5m_vuelos:mde_5m_amba_1.3_2013 en -34.462,-58.500 | devuelve RED_BAND/GREEN_BAND/BLUE_BAND (imagen coloreada), no cota: no se pudo leer la altura',
'http://cultura.sanisidro.gob.ar/festivales/ | 404',
'https://www.zonanortediario.com.ar/20/07/2026/san-isidro-comienzan-obras-estructurales-en-puerto-libre/ y similares | sólo resultado de búsqueda; se usó la nota del Municipio',
'https://www.lanacion.com.ar/buenos-aires/el-bosque-alegre-es-paisaje-protegido-nid1464515/ ; https://publicacionescientificas.fadu.uba.ar/index.php/hisba/article/download/909/1323/ | sólo resultado de búsqueda, no leídos',
'https://normas.gba.gob.ar/documentos/BjbEbmfA.html (Ley 15.190) y BgAaAJHa.html (Ley 15.185) | sólo resultado de búsqueda: son otras áreas (ex golf de Villa Adelina; islas). No encontré ley provincial que declare Bosque Alegre',
'https://overpass-api.de | no se reintentó (d1: conexión reseteada); se usaron los .osm de d1',
]
open(f'{U}/FUENTES.txt','w').write('\n'.join(lines)+'\n'); print(len(lines))
