import os
D='2026-10-03'
S={
'_h2t.py':('(script propio)','Conversor HTML a texto plano usado para los .txt'),
'_fuentes.py':('(script propio)','Arma este FUENTES.txt'),
'ar_ley26363_infoleg_texact.htm':('https://servicios.infoleg.gob.ar/infolegInternet/anexos/140000-144999/140098/texact.htm','Ley 26.363 texto actualizado InfoLEG (art. 4 h: ANSV diseña el sistema de puntos de la LNC; modifica arts. 8, 13, 84, 85 de Ley 24.449). PRIMARIA'),
'ar_ley26363_infoleg_texact.txt':('https://servicios.infoleg.gob.ar/infolegInternet/anexos/140000-144999/140098/texact.htm','Texto plano del anterior'),
'ar_ley26363_infoleg_norma.htm':('https://servicios.infoleg.gob.ar/infolegInternet/anexos/140000-144999/140098/norma.htm','Ley 26.363 texto original (sancionada 9/4/2008). PRIMARIA'),
'ar_dec437_2011_infoleg_texact.htm':('https://servicios.infoleg.gob.ar/infolegInternet/anexos/180000-184999/181142/texact.htm','Decreto nacional 437/2011 texto actualizado (con Dec. 242/2022): Anexo II Sistema de Puntos (20 puntos; 60/120/180 días; recupero a 2 años o cursos de 4 puntos) y Anexo III contenidos mínimos de cursos (12 h parcial / 25 h total). PRIMARIA'),
'ar_dec437_2011_infoleg_texact.txt':('idem','Texto plano del anterior'),
'ar_dec437_2011_infoleg_norma.htm':('https://servicios.infoleg.gob.ar/infolegInternet/anexos/180000-184999/181142/norma.htm','Decreto 437/2011 texto original (11/4/2011). PRIMARIA'),
'ar_dec437_2011_infoleg_norma.txt':('idem','Texto plano del anterior'),
'ansv_aula_virtual_capacitacion.html':('https://capacitacion.seguridadvial.gob.ar/','Aula virtual ANSV: "Curso para infractores de tránsito" para quienes deben cumplir cargas impuestas por Juzgados de Faltas. Oficial'),
'ansv_aula_virtual_capacitacion.txt':('idem','Texto plano'),
'jujuy_minseguridad_tag_sistema_scoring_nacional.html':('https://seguridad.jujuy.gob.ar/tag/sistema-de-scoring-nacional/','Ministerio de Seguridad de Jujuy: partes de inhabilitados por scoring (263 acumulados al 04/03/2024). Oficial provincial'),
'jujuy_minseguridad_tag_sistema_scoring_nacional.txt':('idem','Texto plano'),
'msi_licencias_wayback_20260610.html':('https://web.archive.org/web/20260610053854id_/https://www.sanisidro.gob.ar/licencias','Página municipal "Licencias de conducir" de San Isidro (copia Wayback del 10/06/2026; el sitio original falla por TLS): emite Licencia Nacional de Conducir; requisitos CENAT/CEPAT; sin mención de puntos. Oficial (vía archivo)'),
'msi_licencias_wayback_20260610.txt':('idem','Texto plano'),
'pba_dec751_2023_ficha.html':('https://normas.gba.gob.ar/ar-b/decreto/2023/751/363772','Ficha SINDMA Decreto 751/2023 (BO 07/06/2023). PRIMARIA'),
'pba_dec751_2023_texto.html':('https://normas.gba.gob.ar/documentos/VJ8L3kuJ.html','Decreto 751/2023 PBA: incorpora art. 39 bis al Anexo I del Dec. 532/09 (cursos especiales: los define el Ministerio de Transporte; puede autorizar a municipios). PRIMARIA'),
'pba_dec751_2023_texto.txt':('idem','Texto plano'),
'pba_dec751_2023_original.pdf':('https://normas.gba.gob.ar/documentos/VwGoe3T5.pdf','Decreto 751/2023 copia del original (PDF). PRIMARIA'),
'pba_ley15002_texto.html':('https://normas.gba.gob.ar/documentos/V9Lm6IPB.html','Ley 15.002 PBA (2018) texto: art. 7 incorporó art. 39 bis a Ley 13.927 con el curso "como alternativa de la multa". PRIMARIA'),
'pba_ley15002_texto.txt':('idem','Texto plano'),
'pba_res404_2017_MG_convenio_ansv_lnc_ficha.html':('https://normas.gba.gob.ar/ar-b/resolucion/2017/404/187258','Ficha Res. 404/2017 Ministerio de Gobierno PBA (BO 28100, 28/08/2017). PRIMARIA'),
'pba_res404_2017_MG_convenio_ansv_lnc_texto.html':('https://normas.gba.gob.ar/documentos/x6Ow3atg.html','Res. 404/2017 MG: aprueba Convenio Específico ANSV-PBA sobre otorgamiento y emisión de la LNC; cláusula 8.2 "gestiones tendientes a la implementación del Sistema Nacional de Scoring". PRIMARIA'),
'pba_res404_2017_MG_convenio_ansv_lnc_texto.txt':('idem','Texto plano'),
'pba_gba_noticia_provincia_se_suma_scoring.html':('https://www.gba.gob.ar/transporte/noticias/con_un_plan_de_beneficios_provincia_se_suma_al_sistema_de_scoring','Gobierno PBA, Ministerio de Transporte, 30/12/2022: adhesión anunciada al scoring federal "dentro de los próximos 90 días"; >6.000 inhabilitaciones por alcoholemia en 2022. Oficial'),
'pba_gba_noticia_provincia_se_suma_scoring.txt':('idem','Texto plano'),
'pba_gba_noticia_senado_aprobo_scoring.html':('https://www.gba.gob.ar/seguridadvial/noticias/el_senado_bonaerense_aprob%C3%B3_el_proyecto_de_scoring_enviado_por_d%E2%80%99onofrio','Gobierno PBA, 20/09/2024: el Senado aprobó el proyecto de Scoring; pasa a Diputados. Oficial'),
'pba_gba_noticia_senado_aprobo_scoring.txt':('idem','Texto plano'),
'pba_proyecto_ley_scoring_media_sancion_senado_2024.pdf':('https://dptdsbsas.nyc3.digitaloceanspaces.com/wp-content/uploads/2025/02/21140935/scoring.pdf','Proyecto de ley de scoring (impresión del 18/9/24 de legislativa.senado-ba.gov.ar/Texto_original.aspx; alojado por el medio Diputados Bs As): modifica art. 8 e incorpora art. 8 bis a Ley 13.927 (adhesión a Dec. 437/2011 y 242/2022; bonificaciones). Copia secundaria de documento legislativo'),
'pba_proyecto_ley_scoring_media_sancion_senado_2024.txt':('idem','Texto extraído'),
'pba_mapadelestado_juzgado_administrativo_san_isidro.html':('https://mapadelestado.gba.gob.ar/organismos/3272','Mapa del Estado PBA: "Juzgado Administrativo San Isidro" (Ministerio de Transporte, Juzgados Administrativos de Infracciones de Tránsito Provincial). Oficial'),
'pba_mapadelestado_juzgado_administrativo_san_isidro.txt':('idem','Texto plano'),
'prensa_0223_2026-06-16_scoring.html':('http://www.0223.com.ar/nota/2026-6-16-17-15-0-buscan-implementar-el-scoring-como-funcionaria-el-sistema-que-descuenta-puntos-por-infracciones','0223 (Mar del Plata), 16/06/2026: el proyecto sigue sin tratar en Diputados; el ministro pide sanción "este año". Prensa'),
'prensa_0223_2026-06-16_scoring.txt':('idem','Texto plano'),
'prensa_datadiario_2023-08-16_prueba_piloto_scoring.html':('https://www.datadiario.com/pba/provincia/se-realizo-la-primera-prueba-piloto-del-sistema-de-scoring-en-la-provincia-202381619130','Data Diario, 16/08/2023: prueba piloto de scoring en San Isidro (428 infracciones; 70,8% hombres). Prensa'),
'prensa_datadiario_2023-08-16_prueba_piloto_scoring.txt':('idem','Texto plano'),
'prensa_sudoesteba_2023-08-18_scoring_piloto.html':('https://www.sudoesteba.com/2023-08-18/licencias-de-conducir-avanza-la-aplicacion-del-scoring-en-la-provincia-de-buenos-aires-6571/','SudoesteBA 18/08/2023 (reproduce nota de Página/12): piloto "a través del Juzgado de Faltas de San Isidro", fines de mayo 2023, 428 faltas, 70% velocidad; Dolores en curso; "todavía no se encuentra aplicado". Prensa'),
'prensa_sudoesteba_2023-08-18_scoring_piloto.txt':('idem','Texto plano'),
'prensa_diputadosbsas_marinucci_scoring.html':('https://diputadosbsas.com.ar/legislatura-bonaerense-marinucci-scoring/','Diputados Bs As, 24/02/2025: pruebas piloto en juzgados de San Isidro y Dolores; proyecto con media sanción; enlace al PDF del proyecto. Prensa'),
'prensa_diputadosbsas_marinucci_scoring.txt':('idem','Texto plano'),
'prensa_infobae_2025-10-14_opinion_scoring_pba.html':('https://www.infobae.com/opinion/2025/10/14/buenos-aires-avanza-hacia-un-sistema-unificado-de-puntos-para-las-licencias-de-conducir/','Infobae, columna de opinión 14/10/2025: describe el proyecto con media sanción. Prensa (opinión)'),
'prensa_infobae_2025-10-14_opinion_scoring_pba.txt':('idem','Texto plano'),
'prensa_diariojudicial_caba_scoring_datos.html':('https://www.diariojudicial.com/news-85362-poner-los-puntos-sobre-la-seguridad-vial','Diario Judicial 03/01/2020: CABA, en 10 años 2.889 inhabilitados por puntos y 366.396 conductores perdieron 2.309.406 puntos. Prensa especializada'),
'prensa_diariojudicial_caba_scoring_datos.txt':('idem','Texto plano'),
'busquedas/ngba_busqueda_scoring.html':('https://normas.gba.gob.ar/resultados?q[phrase]=scoring','Resultados SINDMA "scoring" (Dec. 382/2022, Res. 404/2017, Leyes impositivas). Búsqueda'),
'busquedas/ngba_busqueda_sistema_de_puntos.html':('https://normas.gba.gob.ar/resultados?q[phrase]=sistema de puntos','Resultados SINDMA "sistema de puntos" (Dec. 1350/2018). Búsqueda'),
'busquedas/ngba_busqueda_sistema_unificado_de_puntaje.html':('https://normas.gba.gob.ar/resultados?q[phrase]=Sistema Unificado de Puntaje','Resultados SINDMA: "No se han encontrado resultados" (no hay norma provincial publicada con ese nombre). Búsqueda'),
'busquedas/ngba_busqueda_cursos_especiales_concientizacion.html':('https://normas.gba.gob.ar/resultados?q[phrase]=cursos especiales de concientización','Resultados SINDMA: sólo Dec. 751/2023 y Dec. 532/09 (no aparece resolución ministerial de contenidos). Búsqueda'),
'busquedas/ngba_busqueda_trabajo_comunitario.html':('https://normas.gba.gob.ar/resultados?q[phrase]=trabajo comunitario&q[with_some_words]=tránsito infracciones','Resultados SINDMA "trabajo comunitario"+tránsito: ninguna norma provincial de tránsito. Búsqueda'),
'municipios/pinamar_cumplimiento_alternativo_multas.html':('https://pinamar.gob.ar/cumplimientoalternativodemultas/','Municipalidad de Pinamar: cumplimiento alternativo (Ord. 6148/2022): trabajo comunitario o curso, 50 UF por jornada de 4 h; exclusiones. Oficial municipal'),
'municipios/pinamar_cumplimiento_alternativo_multas.txt':('idem','Texto plano'),
'municipios/junin_tareas_comunitarias_transito.html':('https://www.junin.gob.ar/noticia/tareas-comunitarias-por-infraccion-de-transito','Municipio de Junín (PBA), 04/11/2019: Juzgado de Faltas N° 2 aplica tareas comunitarias en lugar de multa según ordenanza reciente. Oficial municipal'),
'municipios/junin_tareas_comunitarias_transito.txt':('idem','Texto plano'),
'municipios/escobar_laotracara_reeducacion_vial_alcoholemia.html':('https://laotracara.info/nota/10490/Reeducacion-vial-como-es-el-proceso-obligatorio-que-deben-seguir-los-infractores-por-alcoholemia','La Otra Cara, 20/12/2024: Escobar, curso municipal de reeducación vial (desde 2019) para infractores por alcohol, después de pagar la multa. Prensa local'),
'municipios/escobar_laotracara_reeducacion_vial_alcoholemia.txt':('idem','Texto plano'),
'evidencia/uk_dft_2018_nsac_impact_evaluation_ipsos.pdf':('https://assets.publishing.service.gov.uk/media/5af4614fe5274a25de49309d/national-speed-awareness-course-evaluation.pdf','Ipsos MORI/U. Leeds para el Department for Transport, "Impact Evaluation of the National Speed Awareness Course", mayo 2018. Evaluación oficial'),
'evidencia/uk_dft_2018_nsac_impact_evaluation_ipsos.txt':('idem','Texto extraído'),
'evidencia/pubmed_15474545.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=15474545&retmode=xml','Masten & Peck, "Problem driver remediation: a meta-analysis of the driver improvement literature", J Safety Research 35(4):403-25, 2004 (resumen). Revisado por pares'),
'evidencia/pubmed_15667817.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=15667817&retmode=xml','Ker, Roberts, Collier et al., "Post-licence driver education... systematic review of RCTs", Accid Anal Prev 37:305-13, 2005 (resumen). Revisado por pares'),
'evidencia/pubmed_12917984.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=12917984&retmode=xml','Misma revisión, versión Cochrane CD003734 (2003) (resumen). Revisado por pares'),
'evidencia/pubmed_7663313.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=7663313&retmode=xml','Wells-Parker et al., meta-análisis de intervenciones de rehabilitación para conductores alcoholizados, Addiction 90:907-26, 1995 (resumen). Revisado por pares'),
'evidencia/pubmed_17873223.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=17873223&retmode=xml','Zambon et al., sistema de puntos de Italia (2003), J Epidemiol Community Health 61(10):877-81, 2007 (resumen). Revisado por pares'),
'evidencia/pubmed_20864703.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=20864703&retmode=xml','Novoa et al., permiso por puntos de España (2006), Am J Public Health 100(11):2220-7, 2010 (resumen). Revisado por pares'),
'evidencia/pubmed_24531113.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=24531113&retmode=xml','Novoa et al., puntos y reforma penal en España sobre lesiones laborales de tránsito, Accid Anal Prev 66:114-9, 2014 (resumen). Revisado por pares'),
'evidencia/pubmed_27085146.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=27085146&retmode=xml','Elvik, meta-análisis de aumentos de multas fijas, Accid Anal Prev 92:202-10, 2016 (resumen). Revisado por pares'),
'evidencia/pubmed_9110036.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=9110036&retmode=xml','DeYoung, Peck, Helander (California DMV), conductores suspendidos/revocados y sin licencia en choques fatales, Accid Anal Prev 29(1):17-23, 1997 (resumen). Revisado por pares'),
'evidencia/pubmed_15288562.xml':('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=15288562&retmode=xml','DeYoung & Gebers (California DMV), riesgo de suspendidos según motivo, J Safety Research 35:287-95, 2004 (resumen). Revisado por pares'),
'evidencia/paper_castillo_castro_2012_points_meta_analysis_idus.pdf':('https://idus.us.es/bitstreams/58bc0025-205e-4c12-b9ed-7f3cce9cbf8d/download','Castillo-Manzano & Castro-Nuño, meta-análisis mundial de sistemas de puntos, Transport Policy 21:191-201, 2012 (repositorio idUS, Univ. de Sevilla). Revisado por pares'),
'evidencia/paper_castillo_castro_2012_points_meta_analysis_idus.txt':('idem','Texto extraído'),
'evidencia/paper_depaola_scoppa_falcone_2013_repec.html':('https://ideas.repec.org/a/spr/empeco/v45y2013i2p965-985.html','De Paola, Scoppa, Falcone, puntos en Italia con regresión discontinua, Empirical Economics 45:965-985, 2013 (resumen RePEc). Revisado por pares'),
'evidencia/paper_depaola_scoppa_falcone_2013_repec.txt':('idem','Texto plano'),
'evidencia/paper_dionne_et_al_2011_restat_repec.html':('https://ideas.repec.org/a/tpr/restat/v93y2011i1p218-227.html','Dionne et al., incentivos por puntos en Quebec, Review of Economics and Statistics 93(1):218-227, 2011 (resumen RePEc). Revisado por pares'),
'evidencia/paper_dionne_et_al_2011_restat_repec.txt':('idem','Texto plano'),
'evidencia/eu_bestpoint_handbook_2012.pdf':('https://archive.etsc.eu/documents/BPHandBook.pdf','BestPoint Handbook (proyecto cofinanciado por DG MOVE, Comisión Europea), ago. 2012. Informe técnico financiado por la CE'),
'evidencia/eu_bestpoint_handbook_2012.txt':('idem','Texto extraído'),
'evidencia/eu_ec_ersosummary_bestpoint.pdf':('https://road-safety.transport.ec.europa.eu/system/files/2021-07/bestpoint.pdf','Ficha del proyecto BestPoint en el sitio de seguridad vial de la Comisión Europea. Oficial UE'),
'evidencia/eu_ec_ersosummary_bestpoint.txt':('idem','Texto extraído'),
'evidencia/es_dgt_2025-01-28_cursos_cambio_actitud.html':('https://www.dgt.es/comunicacion/noticias/20250128-modificaciones-para-un-cambio-de-actitud/','DGT España 28/01/2025: reforma de cursos (Orden INT/914/2024); en 2023 ~4,5 M de puntos perdidos, ~20.300 conductores sin saldo, 82.877 cursos. Oficial'),
'evidencia/es_dgt_2025-01-28_cursos_cambio_actitud.txt':('idem','Texto plano'),
'evidencia/fr_onisr_stageval.html':('https://www.onisr.securite-routiere.gouv.fr/en/node/651','ONISR (Francia): estudio STAGEVAL (Cour d\'appel de Colmar/Univ. de Strasbourg), informe julio 2022; evaluación de participantes, sin medir reincidencia. Oficial'),
'evidencia/fr_onisr_stageval.txt':('idem','Texto plano'),
'evidencia/fr_lcvr_stages_sensibilisation.html':('https://www.violenceroutiere.fr/stages-de-sensibilisation-a-securite-routiere-reponse-educative-conducteurs-infractionnistes/','Ligue contre la violence routière (ONG): "no existe en Francia evaluación epidemiológica con cohorte y grupo testigo" de los stages; 323.096 participantes en 2012. Secundaria'),
'evidencia/fr_lcvr_stages_sensibilisation.txt':('idem','Texto plano'),
'evidencia/mx_itdp_2021_fotocivicas.html':('https://mexico.itdp.org/2021/11/19/fotocivicas-2021/','ITDP México 19/11/2021: presenta estudio de impacto de Fotocívicas con apoyo del BID. Think tank'),
'evidencia/mx_itdp_2021_fotocivicas.txt':('idem','Texto plano'),
'evidencia/mx_itdp_2022_fotocivicas_policy_brief.pdf':('https://mexico.itdp.org/wp-content/uploads/2022/02/1.-Expansion-y-fortalecimiento-del-programa-Fotocivicas-en-CDMX-Policy-Brief.pdf','ITDP/FIA Foundation, "Expansión y fortalecimiento del programa Fotocívicas" (policy brief): -12% siniestros con lesionados a 500 m de cámaras; sin efecto en fallecidos. Think tank (estudio con apoyo BID)'),
'evidencia/mx_itdp_2022_fotocivicas_policy_brief.txt':('idem','Texto extraído'),
'evidencia/paper_gehrsitz_2017_jle_speeding_suspension_strathprints.pdf':('https://strathprints.strath.ac.uk/61623/1/Gehrsitz_JLE_2017_Speeding_punishment_and_recidivism_evidence_from.pdf','Gehrsitz, "Speeding, Punishment, and Recidivism: Evidence from a RDD", J. Law & Economics 60(3), 2017 (versión aceptada, repositorio Strathclyde). Revisado por pares'),
'evidencia/paper_gehrsitz_2017_jle_speeding_suspension_strathprints.txt':('idem','Texto extraído'),
'evidencia/paper_goncalves_mello_nber_w31678_police_discretion.pdf':('https://www.nber.org/system/files/working_papers/w31678/w31678.pdf','Gonçalves & Mello, "Police Discretion and Public Safety", NBER WP 31678, sept. 2023 (no revisado por pares en esta versión). Paper'),
'evidencia/paper_goncalves_mello_nber_w31678_police_discretion.txt':('idem','Texto extraído'),
'evidencia/paper_hansen_2015_aer_abstract.html':('https://www.aeaweb.org/articles?id=10.1257/aer.20130189','Hansen, "Punishment and Deterrence: Evidence from Drunk Driving", AER 105(4):1581-1617, 2015 (página con resumen). Revisado por pares'),
'evidencia/paper_hansen_2015_aer_abstract.txt':('idem','Texto plano'),
'evidencia/paper_barilan_sacerdote_nber_w8638.html':('https://www.nber.org/papers/w8638','Bar-Ilan & Sacerdote, NBER WP 8638 (2001), luego J. Law & Economics 47:1-17 (2004): multas y semáforo en rojo (Israel/EE.UU.). Paper (resumen)'),
'evidencia/paper_barilan_sacerdote_nber_w8638.txt':('idem','Texto plano'),
'evidencia/paper_2023_do_increased_speeding_fines_save_lives_repec.html':('https://ideas.repec.org/a/eee/ecotra/v34y2023ics2212012223000114.html','"Do increased speeding fines save lives?", Economics of Transportation 34, 2023 (doi 10.1016/j.ecotra.2023.100311) (resumen RePEc). Revisado por pares'),
'evidencia/paper_2023_do_increased_speeding_fines_save_lives_repec.txt':('idem','Texto plano'),
'evidencia/us_aamva_suspended_driver_best_practices_ed3.pdf':('https://www.aamva.org/getmedia/b92cc79d-560f-4def-879c-6d6e430e4f4d/Reducing-Suspended-Drivers-and-Alternative-Reinstatement-Best-Practices-Edition-3.pdf','AAMVA (asociación de agencias de tránsito de EE.UU./Canadá), "Reducing Suspended Drivers and Alternative Reinstatement", ed. 3, mayo 2021. Informe técnico sectorial'),
'evidencia/us_aamva_suspended_driver_best_practices_ed3.txt':('idem','Texto extraído'),
'evidencia/crossref_busquedas_evidencia.json':('https://api.crossref.org/works?query.bibliographic=...','Metadatos Crossref (DOI, revista, año, páginas) de los papers buscados. Metadatos'),
}
rows=['archivo | bytes | URL | fecha de consulta | descripción']
prev=None
for f in sorted(S):
    if not os.path.exists(f): print('FALTA',f); continue
    url,desc=S[f]
    if url=='idem': url=prev
    else: prev=url
    rows.append(f'{f} | {os.path.getsize(f)} | {url} | {D} | {desc}')
# check unlisted
for dp,dn,fn in os.walk('.'):
    for x in fn:
        p=os.path.join(dp,x)[2:]
        if p not in S and p!='FUENTES.txt': print('SIN LISTAR',p)
rows.append('')
rows.append('PÁGINAS LEÍDAS O CONSULTADAS Y NO GUARDADAS (fallas, bloqueos o sólo resumen):')
nos=[
'https://www.sanisidro.gob.ar/licencias (y /transito/licencias-de-conducir, /licencias-de-conducir) | falla de certificado TLS con curl y HTTP 503 con WebFetch; se usó la copia de Wayback del 10/06/2026 (guardada)',
'https://www.agn.gov.ar/sites/default/files/informes/2025-023-Informe.pdf | Informe de auditoría AGN sobre la ANSV (2025): falla TLS con curl, 503 con WebFetch y sin copia en Wayback; NO LEÍDO',
'https://www.nhtsa.gov/book/countermeasures-that-work/... y https://www.nhtsa.gov/sites/nhtsa.gov/files/2023-12/countermeasures-that-work-11th-2023-tag_0.pdf | NHTSA "Countermeasures That Work" 2023: HTTP 403; no leído',
'https://www.argentina.gob.ar/noticias/scoring-nacional-buenos-aires-implementara-el-descuento-de-puntos-por-infracciones-de ; .../scoring-federal-se-presento-el-sistema-las-jurisdicciones-para-que-comiencen-utilizarlo-0 ; .../scoring-acuerdo-nacional-... | noticias ANSV/Min. Transporte: HTTP 403; sólo título y resumen del buscador',
'https://www.argentina.gob.ar/seguridadvial/mi-scoring | redirigió a otra página (certificado de seguridad vehicular); descartada',
'https://www.pagina12.com.ar/579830-avanza-la-aplicacion-del-scoring-en-provincia | Página/12 2023: cuerpo no extraíble (JS); se usó la reproducción de SudoesteBA (guardada)',
'https://www.infocielo.com/politica-y-economia/arranca-el-scoring-asi-fue-la-prueba-piloto-del-sistema-que-resta-puntos-la-licencia-conducir-n769646 | HTTP 403',
'https://www.el1digital.com.ar/sociedad/scoring-provincial-un-sistema-que-premia-a-los-buenos-conductores/ | HTTP 403',
'https://diputadosbsas.com.ar/licencia-conducir-puntos-scoring/ (03/08/2022) y https://www.entrelineas.info/articulo/1066/36029/... (06/07/2022) | leídas con curl, no guardadas: el scoring federal entró en vigor el 3/8/2022 y PBA no lo aplicaba',
'https://www.milenio.com/politica/comunidad/fotocivicas-cdmx-disminuyeron-reincidencia-infracciones-semovi | HTTP 403; la afirmación de SEMOVI sobre menor reincidencia queda sin verificar',
'https://alternativaenpapel.com.ar/2024/12/18/reeducacion-vial-... | HTTP 429; se guardó otra nota sobre el mismo programa (La Otra Cara)',
'https://www.gba.gob.ar/seguridadvial/noticias/alcohol_cero_se_afianza_en_la_provincia | HTTP 500',
'https://link.springer.com/article/10.1007/s00181-012-0642-9 | redirige a login; se usó RePEc (guardado)',
'https://api.openalex.org/works/... | HTTP 429 (límite); y https://api.semanticscholar.org/... | resúmenes ocultados por el editor; no guardados',
'https://www.journals.uchicago.edu/doi/10.1086/380471 y https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3064406 | HTTP 403',
'https://www.boletinoficial.gob.ar/detalleAviso/primera/262457/20220506 | URL equivocada (otra norma); Decreto 242/2022 se leyó a través de los textos actualizados de InfoLEG (Dec. 437/2011 y Anexo 2 del Dec. 779/95 en m1)',
'https://www.todojujuy.com/jujuy/scoring-50-inhabilitados-la-ultima-semana-y-mas-1200-que-se-implemento-n265729 | sólo título del buscador (">1.200 inhabilitados en Jujuy"): sin confirmar',
'https://www.estrelladigital.es/... ("24.845 conductores sin puntos en España en 2024") | sólo resumen del buscador; sin confirmar',
'https://www.nber.org/papers/w8496 | descargada por error (otro paper), borrada',
]
rows+=['- '+x+' | '+D for x in nos]
open('FUENTES.txt','w',encoding='utf-8').write('\n'.join(rows)+'\n')
print(len(rows))
