# -*- coding: utf-8 -*-
from content_a import RH

GLOSARIO = dict(id="glosario", runhead=RH, html="""
<h1>Glosario</h1>
<div class="stand">Cuarenta palabras t&eacute;cnicas y siglas que aparecen en el texto, explicadas como se las
explicar&iacute;a a un vecino.</div>
<table>
<colgroup><col style="width:158pt"><col></colgroup>
<tr class="hd"><th>Palabra</th><th>Qu&eacute; quiere decir</th></tr>
<tr><td class="l">Devengado</td><td>El dinero que el Municipio se comprometi&oacute; a cobrar o a pagar, haya entrado o no. Es la factura, no el pago.</td></tr>
<tr><td class="l">Percibido</td><td>El dinero que efectivamente entr&oacute; a la caja. La diferencia con lo devengado no es s&oacute;lo lo que qued&oacute; sin pagar. Tambi&eacute;n incluye los descuentos y las exenciones, es decir, lo que el Municipio decide no cobrar sobre lo ya facturado.</td></tr>
<tr><td class="l">Percepci&oacute;n</td><td>Qu&eacute; porcentaje de lo devengado termin&oacute; entrando a la caja.</td></tr>
<tr><td class="l">Partida</td><td>El dinero que el presupuesto reserva para algo. Por ejemplo, la partida vecinal es el dinero de obra que deciden los vecinos de cada zona.</td></tr>
<tr><td class="l">Gasto r&iacute;gido</td><td>La parte del gasto que no se puede dejar de pagar dentro del a&ntilde;o: sueldos, deuda y contratos ya firmados. En San Isidro es el 73,1%.</td></tr>
<tr><td class="l">Gasto flexible</td><td>La parte del presupuesto que queda y s&iacute; se puede decidir cada a&ntilde;o, porque no est&aacute; atada a sueldos, deudas ni contratos firmados. Son 87.326 millones, el 26,9%. Este programa ocupa el 51,8% de esa parte (3.4).</td></tr>
<tr><td class="l">Ahorro corriente</td><td>El dinero que sobra despu&eacute;s de pagar el funcionamiento diario, antes de invertir en obra.</td></tr>
<tr><td class="l">Resultado financiero</td><td>El dinero que queda al final del a&ntilde;o, despu&eacute;s de pagar todos los gastos, incluida la obra. En 2025 fue de &minus;6.051 millones. Ese a&ntilde;o, el Municipio gast&oacute; m&aacute;s de lo que recibi&oacute;.</td></tr>
<tr><td class="l">Bienes de uso</td><td>Es el nombre contable de la obra p&uacute;blica y del equipamiento. A diferencia de otros gastos, la obra y los equipos quedan y se siguen usando despu&eacute;s de pagarlos.</td></tr>
<tr><td class="l">Pliego</td><td>El documento con las condiciones de una licitaci&oacute;n: qu&eacute; se contrata, c&oacute;mo se trabaja y qu&eacute; sanciones hay si no se cumple. Las empresas que se presentan tienen que aceptarlo.</td></tr>
<tr><td class="l">Adjudicaci&oacute;n</td><td>La decisi&oacute;n del Municipio de darle un contrato a la empresa que gan&oacute; la licitaci&oacute;n. Se hace por decreto.</td></tr>
<tr><td class="l">Coparticipaci&oacute;n</td><td>El dinero que la Provincia le gira a cada municipio seg&uacute;n una f&oacute;rmula de la Ley 10.559. Es el 25% de lo que gasta San Isidro.</td></tr>
<tr><td class="l">NBI</td><td>Necesidades B&aacute;sicas Insatisfechas. Un hogar tiene NBI si le falta alguna condici&oacute;n b&aacute;sica. Por ejemplo, si vive mucha gente en poco espacio, si la vivienda es precaria, si no tiene ba&ntilde;o o si hay chicos que no van a la escuela. En San Isidro es el 3,16% de los hogares.</td></tr>
<tr><td class="l">&Iacute;ndice de necesidad</td><td>Reparte entre las zonas la mitad del dinero de obra que deciden los vecinos. Mira cuatro cosas: NBI, falta de cloaca, falta de gas de red y hacinamiento, que es cuando vive mucha gente en poco espacio. Para cada una, calcula qu&eacute; parte del total de San Isidro est&aacute; en cada zona. Despu&eacute;s saca el promedio de las cuatro. Cuenta hogares, no porcentajes.</td></tr>
<tr><td class="l">TAMAR</td><td>La tasa que los bancos pagan por los plazos fijos grandes. El bono con el que el Municipio se endeud&oacute; en 2026 paga de inter&eacute;s la TAMAR m&aacute;s 7 puntos.</td></tr>
<tr><td class="l">Copyleft</td><td>Un tipo de licencia de software. Obliga a que todo lo que se construya a partir de ese software se publique tambi&eacute;n como libre, para que cualquiera lo pueda usar, copiar y cambiar. Por eso este programa no parte del c&oacute;digo de Decidim, la plataforma de participaci&oacute;n de Barcelona, que tiene esa licencia.</td></tr>
<tr><td class="l">Silencio positivo</td><td>Cuando la ley dice que no contestar equivale a estar de acuerdo. Este programa no lo usa. Si una asociaci&oacute;n de parque no firma la recepci&oacute;n de una obra ni hace observaciones, la obra no se da por aprobada. En ese caso resuelve la Comisi&oacute;n de Obras del Concejo Deliberante.</td></tr>
<tr><td class="l">Radio censal</td><td>Es la zona m&aacute;s chica para la que el Censo publica datos: unas 300 viviendas. San Isidro tiene 360 radios censales. El cap&iacute;tulo 1 usa los datos de los radios para mirar San Isidro de cerca.</td></tr>
<tr><td class="l">Fracci&oacute;n censal</td><td>Es un grupo de radios censales. San Isidro tiene 35 fracciones. La fracci&oacute;n 32, en B&eacute;ccar, es la que tiene m&aacute;s hogares con NBI de todo San Isidro.</td></tr>
<tr><td class="l">UNSO</td><td>Universidad Nacional de San Isidro. Es la universidad p&uacute;blica que este programa propone para dar la tecnicatura.</td></tr>
<tr><td class="l">CFL</td><td>Centro de Formaci&oacute;n Laboral. El CFL 404 Barrio La Cava, de B&eacute;ccar, es el modelo que este programa lleva a las seis zonas (5.3).</td></tr>
<tr><td class="l">Tecnicatura</td><td>Una carrera universitaria corta. Este programa propone una de dos a&ntilde;os, que dar&iacute;a la UNSO en sedes de las seis zonas. El primer a&ntilde;o se cursa, y en el segundo se hacen las pasant&iacute;as. La universidad entrega el t&iacute;tulo.</td></tr>
<tr><td class="l">Pasant&iacute;a</td><td>Un trabajo en el que el estudiante aprende, en proyectos reales. Tiene convenio, un pago, horario limitado, seguro contra accidentes de trabajo (ART) y cobertura de salud, seg&uacute;n la Ley 26.427. Las que propone este programa son dos, de seis meses cada una: una en el Municipio y otra en una empresa de San Isidro. Este programa le garantiza un lugar para hacerla.</td></tr>
<tr><td class="l">Tutor</td><td>Es uno de los profesores del alumno, y lo elige el propio estudiante. Lo acompa&ntilde;a hasta que consigue trabajo. Como pide la ley, la UNSO lo nombra &laquo;docente gu&iacute;a&raquo;. Cada alumno tiene un solo tutor.</td></tr>
<tr><td class="l">Supervisor</td><td>Quien acompa&ntilde;a a los pasantes en el lugar de trabajo. Hay uno cada diez pasantes, y est&aacute; presente todo el horario. En las &aacute;reas del Municipio es un empleado que ya trabaja ah&iacute; y cambia de tarea. Cada empresa pone a alguien que ya trabaja ah&iacute;. La reglamentaci&oacute;n de la ley llama &laquo;tutor&raquo; al supervisor. Este programa, en cambio, usa ese nombre para otra figura (ver &laquo;Tutor&raquo;).</td></tr>
<tr><td class="l">Semillero</td><td>Una ayuda que propone este programa para que el egresado que no queda contratado arme su propia empresa. Tiene tres partes: un a&ntilde;o de acompa&ntilde;amiento para arrancar, un primer cliente y un pr&eacute;stamo. El primer cliente sale de la parte de cada licitaci&oacute;n del Municipio que queda reservada para empresas nuevas de San Isidro. Por cada peso que la empresa consiga de otro lado, el pr&eacute;stamo pone otro.</td></tr>
<tr><td class="l">Profesor digital</td><td>Es la parte de la inteligencia artificial del Municipio que hace de profesor particular. Con cara y voz, le explica al chico sus dudas de la tarea. Le da pistas, nunca la respuesta (5.8).</td></tr>
<tr><td class="l">Prueba sellada</td><td>Una grabaci&oacute;n, una foto o un audio que la inteligencia artificial del Municipio sella en el momento de grabar, con firma digital, hora y lugar. Si despu&eacute;s alguien lo cambia, se nota. Sirve para denunciar un ruido, una coima o una violencia.</td></tr>
<tr><td class="l">Firma digital</td><td>Un sello electr&oacute;nico, hecho con un certificado, que prueba de d&oacute;nde viene un archivo y que nadie lo cambi&oacute; despu&eacute;s. La Naci&oacute;n le da gratis al Municipio el certificado (Ley 25.506).</td></tr>
<tr><td class="l">Huella</td><td>Un c&oacute;digo corto que se saca de un archivo, como una huella digital. Si alguien cambia el archivo, aunque sea un poco, la huella ya no coincide. La huella de cada grabaci&oacute;n de una inspecci&oacute;n llega a la inteligencia artificial del Municipio en el momento de grabar (5.9).</td></tr>
<tr><td class="l">Cadena de custodia</td><td>El registro de qui&eacute;n tuvo una prueba, cu&aacute;ndo y qu&eacute; hizo con ella, desde que se graba hasta que la ve un juez. Sin ella, la prueba pesa menos.</td></tr>
<tr><td class="l">Son&oacute;metro</td><td>El aparato que mide el ruido en decibeles. Para multar, la Ordenanza 8 pide uno de clase 1 o 2, calibrado por un laboratorio en los &uacute;ltimos dos a&ntilde;os y comprobado antes y despu&eacute;s de cada medici&oacute;n.</td></tr>
<tr><td class="l">C&aacute;mara de tramo</td><td>Una c&aacute;mara de velocidad que mide el promedio entre dos puntos, y no la velocidad en un solo lugar. Baja m&aacute;s los choques graves que las fijas (5.11).</td></tr>
<tr><td class="l">Canon</td><td>El pago que hace quien usa un espacio p&uacute;blico para su negocio, como un foodtruck en la costa. Los instructores de las plazas y los artistas a la gorra no pagan canon: se anotan en un registro gratis.</td></tr>
<tr><td class="l">A la gorra</td><td>Cuando el artista act&uacute;a en la calle o en una plaza y el p&uacute;blico le deja lo que quiere. El Municipio no le va a pagar: le va a llevar el sonido y armar el escenario (5.5).</td></tr>
<tr><td class="l">ANMAT</td><td>Administraci&oacute;n Nacional de Medicamentos, Alimentos y Tecnolog&iacute;a M&eacute;dica. Es el organismo nacional que aprueba los medicamentos y los productos m&eacute;dicos, incluido el software que ayuda a diagnosticar (5.6).</td></tr>
<tr><td class="l">IOMA</td><td>Instituto de Obra M&eacute;dico Asistencial. Es la obra social de los empleados p&uacute;blicos de la Provincia de Buenos Aires.</td></tr>
<tr><td class="l">Ordenanza</td><td>La ley municipal. El Concejo Deliberante la vota, y el intendente la pone en vigencia o la rechaza con un veto.</td></tr>
<tr><td class="l">Departamento Ejecutivo</td><td>El intendente y sus secretar&iacute;as, que gobiernan el Municipio. Tambi&eacute;n se lo llama &laquo;el Ejecutivo&raquo;.</td></tr>
<tr><td class="l">Ley Org&aacute;nica de las Municipalidades</td><td>El Decreto-Ley 6769/58, que fija qu&eacute; puede y qu&eacute; no puede hacer un municipio bonaerense. Es de 1958 y sigue vigente.</td></tr>
</table>
""")
