# -*- coding: utf-8 -*-
from content_a import RH

# Correccion 133: las fuentes que colgaban de un parrafo salen de la pagina y
# vienen aca. Las de cuadros y graficos se quedan pegadas a su exhibit.
# Correccion 138 (respuesta 6): van en la misma pagina que la nota de metodo y
# las notas de cada capitulo, al final del documento.
FUENTES_HTML = """
<div class="hairline"></div>
<h2>Las fuentes de lo que afirma el texto</h2>
<p class="tight">Cada cuadro y cada gr&aacute;fico lleva su fuente debajo. &Eacute;stas son las de lo que
afirma el texto, en el orden en que aparecen.</p>
<table>
<colgroup><col style="width:158pt"><col></colgroup>
<tr class="hd"><th>D&oacute;nde</th><th>Fuente</th></tr>
<tr><td class="l">Qu&eacute; proponemos hacer, punto 5 &middot; el 1,84 de la aplicaci&oacute;n de reclamos</td><td>El 1,84: las 49 rese&ntilde;as posteriores al 10 de diciembre de 2023 de la aplicaci&oacute;n municipal de reclamos &laquo;San Isidro Digital&raquo; en Google Play, 39 de ellas de una o dos estrellas; en App Store, otras cinco del mismo per&iacute;odo promedian 1,60. Relevamiento propio del 21 de septiembre de 2026. Los datos crudos, con la fecha y el puntaje de cada rese&ntilde;a y sin nombres de usuarios, est&aacute;n en el repositorio, en <b>informes/05_resenas_app_reclamos.csv</b>, y la metodolog&iacute;a en <b>informes/05_que_dicen_los_vecinos.md</b>. Con la gesti&oacute;n anterior la misma aplicaci&oacute;n promediaba 2,22: no es un problema nuevo, es uno que no se resolvi&oacute; y se agrav&oacute;.</td></tr>
<tr><td class="l">2.2 &middot; lo que se busc&oacute; y no estaba</td><td>Verificado el 20 de septiembre de 2026, sobre el sitio municipal y el archivo de la Wayback Machine.</td></tr>
<tr><td class="l">3.2 &middot; por qu&eacute; baj&oacute; la percepci&oacute;n</td><td>Ordenanza Fiscal 2025 (Ordenanza 9379), publicada en el Bolet&iacute;n Oficial municipal el 26 de diciembre de 2024: art&iacute;culo 51, el descuento de hasta el 10% a quien paga la tasa del a&ntilde;o por adelantado y sin deuda; art&iacute;culo 58, inciso 3, la exenci&oacute;n a los jubilados que cobran hasta tres haberes m&iacute;nimos; art&iacute;culo 143, la exenci&oacute;n de patente a las motos de hasta 150cc. Las m&aacute;s de 400 tasas eliminadas o simplificadas, anunciadas por el Municipio en noviembre de 2024 y aprobadas por el Concejo el 11 de diciembre de 2024, seg&uacute;n &Aacute;mbito y Zona Norte Hoy. La mora de los bonaerenses, del relevamiento del defensor del Pueblo adjunto de la Provincia, Walter Martello, con datos a septiembre de 2026, seg&uacute;n El D&iacute;a del 20 de septiembre de 2026.</td></tr>
<tr><td class="l">3.5 &middot; el bono de 30.000 millones</td><td>Ordenanza Preparatoria N&ordm; 1, expediente 97341-S-2026, aprobada por la Asamblea de Concejales y Mayores Contribuyentes el 8 de julio de 2026; condiciones y resultado de la colocaci&oacute;n del 13 de agosto de 2026 seg&uacute;n la informaci&oacute;n difundida por el Municipio y por el Banco de la Provincia de Buenos Aires, organizador y colocador de la emisi&oacute;n.</td></tr>
<tr><td class="l">3.5 &middot; la base de valuaci&oacute;n: cu&aacute;nto aporta, y qui&eacute;n paga m&aacute;s y qui&eacute;n menos</td><td>C&aacute;lculo propio <b>sobre la parte tierra</b> de la tasa, con las <b>69.258 parcelas</b> del geoservicio de ARBA: 68.644 &mdash;el 99,1%&mdash; cruzan con la tabla de la Ordenanza 8373, publicada en la Ordenanza Impositiva 2016, y con los valores unitarios b&aacute;sicos por macizo de ARBA (Decreto 790/16). Multiplicador, al&iacute;cuota de vivienda y m&iacute;nimos, de la Ordenanza Impositiva 2026. El m&iacute;nimo se compara parcela por parcela con la tierra sola; en los edificios cada departamento paga su propio m&iacute;nimo (art&iacute;culo 1). Las 16.097 parcelas cuya baja frenar&iacute;a el m&iacute;nimo tienen 226 m&sup2; de mediana; las del partido, 298. Lo cobrado va de 7.180,7 millones, si el m&iacute;nimo frena todas las subas de lotes que hoy est&aacute;n bajo el piso, a 7.225,2, si no frena ninguna. Lo que el programa necesita cada a&ntilde;o es la rampa del modelo fiscal: 25%, 50%, 75% y 100% de 7.225,2 millones. <b>Los metros construidos no son p&uacute;blicos</b>: la parte construida de la boleta, que no cambia, queda afuera, y los porcentajes son de la parte tierra. M&eacute;todo, supuestos, datos y c&oacute;digo en informes/09_escenario_b_valuacion.md.</td></tr>
<tr><td class="l">5.3 &middot; qu&eacute; hace hoy el Municipio con el empleo</td><td>Las 131 empresas y los 600 puestos son cifras comunicadas por el propio Municipio, y as&iacute; se las trata. La ausencia de cl&aacute;usulas de empleo local es relevamiento propio de pliegos y normativa publicada, al 21 de septiembre de 2026.</td></tr>
<tr><td class="l">5.3 &middot; las pasant&iacute;as y pr&aacute;cticas que ya existen</td><td>Bolet&iacute;n Oficial Municipal: decretos 374/2025 (Barcel&oacute;, Medicina, sin gasto municipal, hasta 2027), 498/2026 (UCA, Medicina), 775/2026 (UBA, Veterinaria) y 298/2026 (15 pasantes en las fiscal&iacute;as por el convenio de 2003 con el Ministerio P&uacute;blico, Ordenanza 7895: 747.500 $ por mes desde marzo de 2026) y 64/2026 (designaci&oacute;n en calidad de becarios); ninguno de los decretos encontrados cita la Ley 26.427 ni fija horas; Ordenanza 8874 de 2016 (Guardaparques, ad honorem); decretos 1604 y 1766 de 2021 (UNSO). Favaloro: nota del Municipio del 3 de septiembre de 2026. UNSO: Zona Norte Visi&oacute;n, 16 de junio de 2025.</td></tr>
<tr><td class="l">5.3 &middot; la pasant&iacute;a, el tope y la cl&aacute;usula del 75%</td><td>Ley 26.427 de pasant&iacute;as educativas, art&iacute;culos 1, 2, 10, 12, 13, 15, 16, 19 y 21, y su reglamentaci&oacute;n, Resoluci&oacute;n conjunta 825/2009 y 338/2009, art&iacute;culos 2, 12, 13 y 14: tope del 7% de la planta en los organismos p&uacute;blicos, un tutor de la organizaci&oacute;n &mdash;en este programa, el supervisor&mdash; cada diez pasantes, presente todo el horario, y la llave de la Provincia para la formaci&oacute;n profesional; Resoluci&oacute;n 5356/24 de la Direcci&oacute;n General de Cultura y Educaci&oacute;n, art&iacute;culos 4, 5 y 20. Planta: 7.946 cargos del Departamento Ejecutivo en el Formulario F6 del presupuesto 2026, Ordenanza 9422, le&iacute;dos jurisdicci&oacute;n por jurisdicci&oacute;n (en el repositorio, data/f6_cargos_2026.csv); el Concejo Deliberante tiene 416. Empleo privado registrado del partido, 93.071 puestos en diciembre de 2025: Observatorio de Empleo y Din&aacute;mica Empresarial, &laquo;Empleo y remuneraciones por departamento&raquo;, tabla 1. La UNSO: oferta acad&eacute;mica al 29 de septiembre de 2026, Reglamento General Acad&eacute;mico (Res. CS 25/2025, art&iacute;culos 3 y 13) y Reglamento de Equivalencias (Res. CS 26/2023); Ley 24.521, art&iacute;culos 7 y 29; carreras de pregrado, Resoluci&oacute;n 2598/2023 del Ministerio de Educaci&oacute;n. Precedentes: Ordenanza 1312/2019 de Rauch; convenios de la UNICEN con Olavarr&iacute;a (2020), Necochea (2022) y Las Flores (2024); Ordenanza 10.198/2022 de Chivilcoy; extensiones &aacute;ulicas de la UTN en Escobar y Z&aacute;rate. Plan FinEs: convocatoria bonaerense de 2026. Cobertura de salud del pasante: Resoluci&oacute;n 1225/2009 de la Superintendencia de Servicios de Salud. ART: Provincia ART, 3,275%, Decreto 1587/2025. El 75%: ordenanzas 9/2022 de General Guido y 2279/2020 de San Andr&eacute;s de Giles; leyes 2750 de Neuqu&eacute;n y 2743 de Santa Cruz; Corte Suprema, Argenova (2010); C&aacute;mara Contencioso Administrativa de Mar del Plata, Wayro contra Olavarr&iacute;a (2022).</td></tr>
<tr><td class="l">5.3 &middot; qu&eacute; se estudia en la tecnicatura</td><td>LinkedIn News, &laquo;Jobs on the Rise 2026: The 25 fastest-growing roles in the U.S.&raquo;, 7 de enero de 2026: empleos iniciados entre enero de 2023 y julio de 2025. Puesto 1, AI engineers (LangChain, RAG y PyTorch; mediana de experiencia previa, 3,7 a&ntilde;os; 26,2% remoto); 2, AI consultants (30,3%); 4, data annotators (27,5%); 17, datacenter technicians (3,6%).</td></tr>
<tr><td class="l">5.3 &middot; el semillero, la subcontrataci&oacute;n y el pago a quince d&iacute;as</td><td>El 20%: Code de la commande publique, art&iacute;culo R2213-5 (Francia, desde el 1 de enero de 2025); Ley 6021, art&iacute;culo 9 ter (Provincia de Buenos Aires, 30% de pymes en la obra p&uacute;blica provincial). Pago y anticipo: Tribunal de Cuentas bonaerense, dict&aacute;menes 32941 (San Miguel, 2022), 5714 (La Matanza, 2012) y 29715 (Carlos Tejedor, 2018); Decreto 2980/00, art&iacute;culos 74 y 100; C&oacute;digo Civil y Comercial, art&iacute;culos 1614 a 1621. La morosidad: Comisi&oacute;n Europea, COM(2020)103. Los quince d&iacute;as: OMB M-11-32 (Estados Unidos, 2011), y Barrot y Nanda, Journal of Finance, 2020. Yozma: OCDE (2003). El fondo nacional: Decreto 1048/2024. El detalle, con los montos y cada fuente, en <b>informes/10_semillero.md</b> del repositorio.</td></tr>
<tr><td class="l">5.5 &middot; la costa: Per&uacute;, el ba&ntilde;o y la arena</td><td>Calidad del agua: red nacional de monitoreo de la costa (estaciones SI021 a SI024), recalculada desde sus datos abiertos; valor gu&iacute;a de los Niveles Gu&iacute;a Nacionales para recreaci&oacute;n humana (Subsecretar&iacute;a de Recursos H&iacute;dricos). Decreto 805/2025, art&iacute;culo 16; Ordenanza 5304 del 19 de enero de 1978, art&iacute;culos 2 y 4; las jornadas de voluntarios, seg&uacute;n el Municipio (2025). Pacheco: Decreto 2559 del 19 de agosto de 2014 (Bolet&iacute;n Oficial 913, p&aacute;gina 41); <i>Clar&iacute;n</i>, 18 de septiembre de 2014; im&aacute;genes satelitales de 2013 a 2026 cruzadas con la altura del r&iacute;o, c&aacute;lculo propio. Bosque Alegre: Decreto 910/2012. Convenio por la calle Paran&aacute;: Ordenanza 8935; comit&eacute; de cuenca: Resoluci&oacute;n 541/2018 de la Autoridad del Agua. Detalle en <b>informes/11_costa.md</b>, <b>informes/15_arena.md</b> e <b>informes/16_agua_y_costa.md</b>.</td></tr>
<tr><td class="l">5.5 &middot; qu&eacute; quiere decir &laquo;no apto&raquo;</td><td>EPA de los Estados Unidos, Recreational Water Quality Criteria 2012, tabla 1, p. 6 (36 casos cada 1.000 ba&ntilde;istas m&aacute;s que entre los que no se meten, con una media de 126 <i>E. coli</i>) y p. 14, y &laquo;What affects human health at the beach&raquo;; CDC, &laquo;Preventing diarrheal illnesses&raquo;, 2025; OMS, Guidelines for safe recreational water environments, 2003, p. 53 y tabla 4.7, p. 70, mantenidos en 2021, tabla 2.1. La lluvia: Health New Zealand, 48 horas; OMS 2021, p. 54; Uruguay, Protocolo Nacional de Actuaci&oacute;n, versi&oacute;n 6, 2022, p. 4 (m&aacute;s de 25 mil&iacute;metros en 24 horas).</td></tr>
<tr><td class="l">5.5 &middot; Montevideo y los jueces</td><td>Uruguay, Decreto 226/025, art&iacute;culos 15 a 17; Intendencia de Montevideo, comunicados semanales de playas de enero a marzo de 2026 y datos abiertos (Montevidata), consultados el 1 de octubre de 2026; Digesto departamental, art&iacute;culo D.2348. Suprema Corte de la Provincia de Buenos Aires: C 111.115, &laquo;Brandan c/ Municipalidad de General Pueyrredon&raquo;, 3 de diciembre de 2014, y A 71.485, &laquo;Amaya c/ Municipalidad de Villa Gesell&raquo;, 4 de junio de 2014. Corte Suprema de Justicia de la Naci&oacute;n: &laquo;Ramos c/ Provincia de C&oacute;rdoba&raquo;, Fallos 328:2546, 28 de junio de 2005. Ley 14.798, art&iacute;culos 2, 5, 19 y 22. Los guardavidas del Municipio: RESFC-2026-717.</td></tr>
<tr><td class="l">5.5 &middot; cu&aacute;nto cuesta la costa</td><td>El piloto: precios del Decreto 1077/2025, anexo II (arena fina, geotextil, nivelaci&oacute;n, plantas y vallado de la zona 2) y del Decreto 367/2025 (gaviones), llevados a diciembre de 2025 con el IPC; reponer del 5% al 25% de la arena por a&ntilde;o, c&aacute;lculo propio con la Playa del Cerro de Montevideo y la bah&iacute;a de Delaware (Psuty y otros, 2018). Los guardavidas: categor&iacute;a 12 del art&iacute;culo 6 de la Ordenanza de Presupuesto 2026, con la bonificaci&oacute;n del 50% de la Ordenanza 9422, y turnos de seis horas (Ley 14.798, art&iacute;culo 16); bote y desfibrilador, precios de avisos de octubre de 2026. Las muestras: precio de lista de un laboratorio privado, octubre de 2026. Redes, barrera y cuadrilla: <b>informes/11_costa.md</b>; el diagn&oacute;stico de Per&uacute;: <b>informes/16_agua_y_costa.md</b>.</td></tr>
<tr><td class="l">5.5 &middot; la recolecci&oacute;n y la antig&uuml;edad de sus trabajadores</td><td>Convenio colectivo 40/89, &iacute;tems 5.3.3, 5.3.6, 5.3.8 y 6.1.5, y su escala de diciembre de 2025 (Disposici&oacute;n 2248/2025); Ley de Contrato de Trabajo, art&iacute;culos 225, 228 y 245, en el texto de la Ley 27.802; pliego de la Licitaci&oacute;n 997/2013 de la Ciudad de Buenos Aires, art&iacute;culo 48. Cu&aacute;ntos trabajadores y con cu&aacute;nta antig&uuml;edad es estimaci&oacute;n propia &mdash;de 350 a 600, de 8 a 16 a&ntilde;os&mdash;, porque no son datos p&uacute;blicos. Detalle en <b>informes/12_recoleccion.md</b>.</td></tr>
<tr><td class="l">5.5 &middot; d&oacute;nde se multa el ruido de escape</td><td>Nueva York: Departamento de Protecci&oacute;n Ambiental, informes anuales del programa de c&aacute;maras de ruido 2024 y 2025 (1.602 actas de junio de 2021 a diciembre de 2024; 1.691 en 2025 sobre 15.994 eventos), comunicado 22-005 de febrero de 2022 y p&aacute;gina del C&oacute;digo de Ruido (escape: de 800 a 2.625 d&oacute;lares). Kensington y Chelsea: consulta de renovaci&oacute;n de la orden de espacio p&uacute;blico, diciembre de 2024 (1.615 infracciones y 577 multas). Reino Unido: Departamento de Transporte, informe T0218, fase 3, partes B y C (revisi&oacute;n manual; dos casos genuinos por d&iacute;a). Taiw&aacute;n: Ministerio de Ambiente. Francia: Ministerio de la Transici&oacute;n Ecol&oacute;gica y Cerema, diciembre de 2025. Jap&oacute;n: NTSEL, foro de 2021. Cornell Tech, 2025. Consultados el 1 de octubre de 2026.</td></tr>
<tr><td class="l">5.5 &middot; el urbanismo que no pasa por el Concejo</td><td>El conteo de decretos es relevamiento propio del Bolet&iacute;n Oficial Municipal, febrero de 2024 a septiembre de 2026; las excepciones, de la lectura de cada acto (C&oacute;digo de Ordenamiento Urbano, art&iacute;culos 1.1.2.6 y 1.2.1.1; decretos 540, 545 y 791 de 2025, por las calles no cedidas; decretos 386, 484, 560 y 628 de 2026, sin anexos publicados). La Ordenanza 9432: su expediente y la versi&oacute;n taquigr&aacute;fica de la sesi&oacute;n del 6 de mayo de 2026. La cautelar de Boulogne: causa SI-26403-2025, resoluciones del 18 de julio y del 30 de diciembre de 2025. La valorizaci&oacute;n: Ley 14.449, art&iacute;culo 50; Ordenanza 8961 de 2017; La Plata, 15%. Las objeciones de los vecinos, de la prensa local, en <b>informes/05_que_dicen_los_vecinos.md</b>; el resto, en <b>informes/13_urbanismo.md</b>.</td></tr>
<tr><td class="l">5.5 &middot; Catalejo y Barisidro</td><td>El permiso de 1996: Decreto 1189/1996, transcripto en el Decreto 605/2025; la habilitaci&oacute;n, Decreto 1380/2008 y el convenio de devoluci&oacute;n de Catalejo. Las clausuras: Comunicaci&oacute;n 214 del Concejo Deliberante, del 7 de agosto de 2024, aprobada por unanimidad. La devoluci&oacute;n de Catalejo: convenio registrado por el Decreto 1778/2024; la revocaci&oacute;n del permiso de Barisidro: Decreto 605/2025. Las demoliciones: nota del Municipio del 17 de junio de 2025 y, la de Barisidro, <i>La Noticia Web</i> (21 de agosto de 2025) y <i>Zonales</i> (26 de agosto de 2025); el acto que las autorice se busc&oacute; en el Bolet&iacute;n Oficial de 2024 a 2026 y no se encontr&oacute;. Lo que contaron quienes explotaban los locales, recogido en <b>informes/17_costa_viva.md</b>, sin nombres. Las direcciones, de la cobertura period&iacute;stica de junio y julio de 2025 y de los comunicados del propio Municipio; el conteo de firmas y la fecha de apertura, de la petici&oacute;n en Change.org, relevada el 21 de septiembre de 2026. Los 9.775 m&sup2; son la superficie que,
seg&uacute;n el Municipio, pas&oacute; al dominio p&uacute;blico (citado por Diario Lo Nuestro, 2026); la estructura de
Catalejo, &laquo;de m&aacute;s 1000 metros cuadrados&raquo;, sale de la nota del Municipio del 17 de junio de 2025. La tenencia de la costa: convenio con la Provincia del 20 de marzo de 2026, por diez a&ntilde;os desde el acta de entrega (Resoluci&oacute;n 138/2026 del Ministerio de Econom&iacute;a provincial, Bolet&iacute;n Oficial del 7 de agosto de 2026), aprobado por la Ordenanza 9430 del 15 de abril de 2026 (Decreto 465/2026). El 40% del canon para la Provincia: art&iacute;culo 38 del Decreto-Ley 9533/80, en el texto de la Ley 15.558 (diciembre de 2025), y cl&aacute;usula cuarta del convenio. El relevamiento de reclamos vecinales est&aacute; en <b>informes/05_que_dicen_los_vecinos.md</b> del repositorio.</td></tr>
<tr><td class="l">5.5 &middot; la costa toda la semana</td><td>Los conteos que faltan, las 145 actividades de invierno de 2026, las distancias a pie desde las estaciones (c&aacute;lculo propio sobre OpenStreetMap) y lo que ya funciona en la semana, seg&uacute;n el Municipio: <b>informes/17_costa_viva.md</b>. El tiempo real: Trenes Argentinos, preguntas frecuentes (&laquo;podr&aacute;s ver en tiempo real los horarios de llegada y salida de los trenes en cada una de las estaciones&raquo;), y Buenos Aires Data, API Transporte P&uacute;blico, recurso &laquo;Trenes&raquo; y aviso de suspensi&oacute;n, consultados el 2 de octubre de 2026. La Reserva: Plan de Manejo de 2012 (alumnos de 1998) y <i>La Nueva</i>, 20 de mayo de 2018. Docklands: Ciudad de Melbourne, Docklands Summit, 2022. El conteo: c&aacute;mara de una compra de la Ciudad de Buenos Aires (Buenos Aires Compras, adjudicada el 23 de septiembre de 2025) y columna, tablero y cable del contrato de alumbrado de San Isidro (Decreto 405/2025), llevados a diciembre de 2025, sin montaje ni programa; el mantenimiento, 10% por a&ntilde;o, es un supuesto.</td></tr>
<tr><td class="l">5.5 &middot; la Escuela N&aacute;utica en los parques de la costa</td><td>Hoy: p&aacute;gina de N&aacute;utica del Municipio (1 de octubre de 2026) y su convocatoria de 2025 (Sal&oacute;n N&aacute;utico Argentino, 19 de febrero de 2025); la bajada, nota del Municipio del 17 de junio de 2025. Parques y orillas: imagen satelital y OpenStreetMap, sin visita; &aacute;reas protegidas, Ordenanzas 6541/1988 y 8461/2009 y Decreto 910/2012. Agua: CIAM, estaciones SI021 a SI024, 2004 a 2025; Texas, t&iacute;tulo 30, §307.7(b)(1)(A)(iii): 630 <i>E. coli</i> de media geom&eacute;trica para pesca, canoa y kayak (§307.3), ac&aacute; por muestra, que es m&aacute;s exigente; el windsurf, OMS 2021, p. 4, y Resoluci&oacute;n 125/2016. Prefectura, Ordenanzas 3-17 y 1-18 (DPSN). Costos, en pesos de diciembre de 2025: m&oacute;dulo de la Ciudad (Buenos Aires Compras, 17 de diciembre de 2025); deck y bajada al precio del entablonado de compras municipales bonaerenses, la bajada estimada en 2 por 10 a 25 metros; equipos y bote, tiendas n&aacute;uticas, octubre de 2026; profesores, Presupuesto 2026, art&iacute;culo 23, categor&iacute;a 991, con aguinaldo y cargas, 108 horas por semana; reposici&oacute;n, bote y mantenimiento, 15%, 10% y 5% por a&ntilde;o, supuestos; a&ntilde;o por a&ntilde;o, con dos puestos de agua abierta el primer a&ntilde;o y uno en cada uno de los siguientes. Deportes: Situaci&oacute;n Econ&oacute;mico-Financiera 2025, programas 45 y 35.</td></tr>
<tr><td class="l">5.5 &middot; cemento o naturaleza</td><td>Decreto 1077/2025 (ampliaci&oacute;n del contrato de espacios verdes, Licitaci&oacute;n P&uacute;blica 62/2024, y precios de su anexo desde marzo de 2025); Licitaciones P&uacute;blicas 32/2025 y 53/2025 (mobiliario y juegos); Ordenanza 9395 y Decreto 614/2025; la obra &Aacute;guila&ndash;Alvear, seg&uacute;n el Municipio, julio de 2026, sin acto publicado hasta el Bolet&iacute;n 1238. Narayan y otros, 2016; Gittman y otros, 2014. Los senderos, con los precios del mismo contrato. Detalle en <b>informes/14_parques_y_costa.md</b> y <b>informes/16_agua_y_costa.md</b>.</td></tr>
<tr><td class="l">5.5 &middot; los parques no se tocan</td><td>Decreto-Ley 8912/77, art&iacute;culo 60, en el texto de la Ley 13.127 (&laquo;Por ninguna raz&oacute;n podr&aacute; modificarse el destino de las &aacute;reas verdes y libres p&uacute;blicas&raquo;); Decreto-Ley 9533/80, art&iacute;culo 1; Ley Org&aacute;nica de las Municipalidades, art&iacute;culo 56; Ley 12.704, art&iacute;culo 1 (las &aacute;reas &laquo;deber&aacute;n ser declaradas por ley&raquo;); Ley 15.190, que declar&oacute; Paisaje Protegido de Inter&eacute;s Provincial al Golf de Villa Adelina; Ley 10.907, art&iacute;culo 7; Ordenanzas 6541/1988, 8461/2009, 8651 y 9351. Las normas provinciales, consultadas en normas.gba.gob.ar el 2 de octubre de 2026.</td></tr>
<tr><td class="l">5.5 &middot; los vecinos que ya cuidan sus parques</td><td>Asamblea del Parque del &Aacute;guila: saludo en la versi&oacute;n taquigr&aacute;fica de la 3&ordf; sesi&oacute;n ordinaria del Concejo Deliberante, 1 de abril de 2026, p&aacute;gina 34. Asamblea Bosque Alegre: <i>La Naci&oacute;n</i>, 17 de abril de 2012 (&laquo;un proyecto alternativo con 4000 adhesiones&raquo;).</td></tr>
<tr><td class="l">5.6 &middot; el recorrido por los hospitales</td><td>El recorrido por los hospitales municipales, la fila de 37 personas, el turno de endocrinolog&iacute;a de cinco meses y la falta de reactivos son de la cobertura period&iacute;stica del <b>3 de junio de 2024</b>. <b>No se encontr&oacute; ning&uacute;n relevamiento independiente posterior</b>, de modo que el dato describe junio de 2024 y no necesariamente hoy. El detalle, con cada cita y su fecha, en <b>informes/05_que_dicen_los_vecinos.md</b> del repositorio.</td></tr>
<tr><td class="l">5.7 &middot; el mapa de incidentes que no existe</td><td>Verificado el 20 de septiembre de 2026, sobre el sitio municipal y el archivo de la Wayback Machine.</td></tr>
<tr><td class="l">5.7 &middot; las c&aacute;maras</td><td>Las cifras de c&aacute;maras e inversi&oacute;n son comunicaciones del propio Municipio entre 2025 y 2026, y as&iacute; se las trata. El relevamiento de testimonios vecinales &mdash;Reddit, peticiones, rese&ntilde;as de las aplicaciones municipales y prensa local, con la fecha y la localidad de cada dato&mdash; est&aacute; en <b>informes/05_que_dicen_los_vecinos.md</b> del repositorio. <b>Verificado el 21 de septiembre de 2026.</b></td></tr>
<tr><td class="l">5.12 &middot; un Municipio que atiende los siete d&iacute;as</td><td>Sin costo extra en sueldos: Ley 14.656, art&iacute;culos 6 y 65 (su r&eacute;gimen supletorio no rige donde hay convenio propio); convenio de San Isidro, Ordenanza 8850/2015, texto ordenado por el Decreto 1703/2019, art&iacute;culos 12 y 33; Ordenanza 9422 (Presupuesto 2026), art&iacute;culo 10: la hora extra se paga s&oacute;lo por el trabajo fuera del horario normal. Los horarios: sitio oficial del Municipio, consultado el 2 de octubre de 2026, y nota del 147 del 22 de enero de 2025. C&oacute;rdoba: cordoba.gob.ar, 10 de marzo de 2024 y 1 de octubre de 2026; La Plata: cam.laplata.gob.ar.</td></tr>
<tr><td class="l">6.1 &middot; c&oacute;mo abr&iacute;a su ciclo el presupuesto participativo de la Ciudad</td><td>Reglamento del Presupuesto Participativo de la Ciudad de Buenos Aires, Consejo del Presupuesto Participativo, mayo de 2004, puntos 4.2 (plenario de apertura: informar a los vecinos y considerar el diagn&oacute;stico) y 4.8 (plenario de cierre: votaci&oacute;n de las prioridades), y su cronograma: apertura del 24 de mayo al 4 de junio, cierre del 2 al 5 de agosto; buenosaires.gob.ar/areas/hacienda/pp, consultado el 30 de septiembre de 2026.</td></tr>
</table>
"""
